<?php
/**
 * Created by PhpStorm.
 * User: user
 * Date: 21.02.17
 * Time: 16:33
 */

namespace Drupal\form_module\Form;

use Drupal\Core\Database\Database;
use Drupal\Core\Form\FormBase;
use Drupal\Core\Form\FormStateInterface;
use Drupal\form_module\Plugin\Block\Form_Block;


class Form_About extends FormBase {

  public function getFormId() {
    return 'form_module_about_form';
  }

  public function buildForm(array $form, FormStateInterface $form_state){
    $form['first_name'] = array(
      '#type' => 'textfield',
      '#title' => $this->t('First Name'),
      '#required' => TRUE,
    );
    $form['last_name'] = array(
      '#type' => 'textfield',
      '#title' => t('Last Name'),
      '#required' => TRUE,
    );

    $form['city'] = array(
      '#type' => 'textfield',
      '#title' => t('City'),
      '#devault_value' => '',
    );
    $form['message'] = array(
      '#type' => 'textarea',
      '#title' => t('Message'),
    );
    $form['submit'] = array(
      '#type' => 'submit',
      '#value' => $this->t('Save'),
    );
    return $form;

  }

  public function validateForm(array &$form, FormStateInterface $form_state) {
    // TODO: Change the autogenerated stub
    if ($form_state->getValue('first_name') == 'vlas') {
      $form_state->setErrorByName('first_name', t('This name is blocked on site!'));
    }
  }

  public function submitForm(array &$form, FormStateInterface $form_state) {
//    parent::submitForm($form, $form_state); // TODO: Change the autogenerated stub
    $form_data = [
      'first_name' => $form_state->getValue('first_name'),
      'last_name' => $form_state->getValue('last_name'),
      'city' => $form_state->getValue('city'),
      'message' => $form_state->getValue('message'),
    ];

    $db = Database::getConnection();

    $db->insert('form_module')
      ->fields($form_data)
      ->execute();
    drupal_set_message(t('Succesfully saved'));

//    db_insert('form_module')
//      ->fields($form_data)
//      ->execute();
//    drupal_set_message('Succesfully saved');
  }

}
